name: lambda
version: 0.1.0.0
github: ""
license: MIT
author: "Giuseppe Lomurno"
maintainer: "lomurno.giuseppe97@gmail.com"
copyright: "MIT"

synopsis: Pet language
category: Language

description: Please see the README

dependencies:
- base >= 4.7 && < 5
- prettyprinter >= 1.2 && < 2
- prettyprinter-ansi-terminal >= 1.1 && < 2

library:
  source-dirs: src

executables:
  lambda-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall -Wno-unticked-promoted-constructors
    dependencies:
    - lambda

tests:
  lambda-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda

